#pragma once

#include <string>

//
// weights generated by "genWeightsFromSK_NIWG2015.exe"
// are used to study uncertinties on neutron tagging efficiency
// due to Xsec uncertainties listed on
//
// 	https://www.t2k.org/nd280/physics/xsec/docs/xsec-niwg-doc/niwg2016
//
// In "genWeightsFromSK_NIWG2015.exe", a set of 135 weights are generated.
// However, I do not need to use all of them, so only the following weights
// are considered in my studies.
//
// R.Akutsu - 28/9/2018
//

namespace WgtXSec{

	const int N_XSEC_WGT				=31;

	enum E_XSEC_WGT{ SF_RFGRelRPA		=128,
					 pF_O16_P1SIG		=11,
					 pF_O16_M1SIG		=9,
					 Eb_O16_P1SIG		=25,
					 Eb_O16_M1SIG		=23,
					 MEC_Norm_O16_P1SIG	=39,
					 MEC_Norm_O16_M1SIG	=37,
					 MaCCQE_P1SIG		=46,
					 MaCCQE_M1SIG		=44,
					 CA5RES_P1SIG		=53,
					 CA5RES_M1SIG		=51,
					 MaNFFRES_P1SIG		=60,
					 MaNFFRES_M1SIG		=58,
					 BgSclRES_P1SIG		=67,
					 BgSclRES_M1SIG		=65,
					 SCCVecQE_P1SIG		=74,
					 SCCVecQE_M1SIG		=72,
					 SCCAxlQE_P1SIG		=81,
					 SCCAxlQE_M1SIG		=79,
					 PsFF_P1SIG			=88,
					 PsFF_M1SIG			=86,
					 ccnueE0_P1SIG		=95,	
					 ccnueE0_M1SIG		=93,	
					 dismpishp_P1SIG	=102,
					 dismpishp_M1SIG	=100,
					 cccohE0_P1SIG		=109,
					 cccohE0_M1SIG		=107,
					 nccohE0_P1SIG		=116,
					 nccohE0_M1SIG		=114,
					 ncotherE0_P1SIG	=123,
					 ncotherE0_M1SIG	=121
				 };
				

	const std::string S_XSEC_WGT[ N_XSEC_WGT ]=
				{ "SF2RFGRelRPA",
			  	  "pFO16_p1Sig",
			  	  "pFO16_m1Sig",
			  	  "EbO16_p1Sig",
			  	  "EbO16_m1Sig",
			  	  "MECNormO16_p1Sig",
			  	  "MECNormO16_m1Sig",
			  	  "MaCCQE_p1Sig",
			  	  "MaCCQE_m1Sig",
			  	  "CA5RES_pSig",
			  	  "CA5RES_m1Sig",
			  	  "MaNFFRES_p1Sig",
			  	  "MaNFFRES_m1Sig",
			  	  "BgSclRES_p1Sig",	
			  	  "BgSclRES_m1Sig",
			  	  "SCCVecQE_p1Sig",
			  	  "SCCVecQE_m1Sig",
			  	  "SCCAxlQE_p1Sig",
			  	  "SCCAxlQE_m1Sig",
			  	  "PsFF_p1Sig",
			  	  "PsFF_m1Sig",
			  	  "ccnueE0_p1Sig",	
			  	  "ccnueE0_m1Sig",	
			  	  "dismpishp_p1Sig",
			  	  "dismpishp_m1Sig",
			  	  "cccohE0_p1Sig",
			  	  "cccohE0_m1Sig",
			  	  "nccohE0_p1Sig",
			  	  "nccohE0_m1Sig",
			  	  "ncotherE0_p1Sig",
			  	  "ncotherE0_m1Sig"
			    };

	const int Bin2Dial[ N_XSEC_WGT ]=
				{ 	(int)SF_RFGRelRPA,
					(int)pF_O16_P1SIG,
					(int)pF_O16_M1SIG,
					(int)Eb_O16_P1SIG,
					(int)Eb_O16_M1SIG,
					(int)MEC_Norm_O16_P1SIG,
					(int)MEC_Norm_O16_M1SIG,
					(int)MaCCQE_P1SIG,
					(int)MaCCQE_M1SIG,
					(int)CA5RES_P1SIG,
					(int)CA5RES_M1SIG,
					(int)MaNFFRES_P1SIG,
					(int)MaNFFRES_M1SIG,
					(int)BgSclRES_P1SIG,
					(int)BgSclRES_M1SIG,
					(int)SCCVecQE_P1SIG,
					(int)SCCVecQE_M1SIG,
					(int)SCCAxlQE_P1SIG,
					(int)SCCAxlQE_M1SIG,
					(int)PsFF_P1SIG,
					(int)PsFF_M1SIG,
					(int)ccnueE0_P1SIG,
					(int)ccnueE0_M1SIG,
					(int)dismpishp_P1SIG,
					(int)dismpishp_M1SIG,
					(int)cccohE0_P1SIG,
					(int)cccohE0_M1SIG,
					(int)nccohE0_P1SIG,
					(int)nccohE0_M1SIG,
					(int)ncotherE0_P1SIG,
					(int)ncotherE0_M1SIG
				};
}
